version: '3'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - .:/var/www/
      - .config/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .config/etc/supervisor/conf.d/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    networks:
      - laravel_network
    ports:
      - 8085:80
    restart: on-failure
    depends_on:
      - php
      - composer
      - mysql

  php:
    image: php:fpm
    volumes:
      - .:/var/www/
    networks:
      - laravel_network
    restart: on-failure

  composer:
    build:
      context: .
      dockerfile: .docker/composer/Dockerfile
    volumes:
      - ./:/app
    command: ./build.sh

  mysql:
    image: mysql:latest
    networks:
      - laravel_network
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=password
    restart: on-failure

networks:
  laravel_network:
    driver: bridge
